name: Send Email on Push

on:
  push:
    branches: [master]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyyaml

      - name: Send email automatically with commit message
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          WHO: ibrahim
          MESSAGE: ${{ github.event.head_commit.message }}
        run: python email_sender.py
